import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/component/Header'
import Banner from '@/component/Banner'
import ProductFeed from '@/component/ProductFeed'
const inter = Inter({ subsets: ['latin'] })

export default function Home({products}) {
  return (
    <div >
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
       
      </Head>
      <Header />
      <main className="max-w-screen-lg bg-gray-100 mx-auto">
      
        <Banner/>

   
        <ProductFeed products={products}/>
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const products = await fetch ("https://fakestoreapi.com/products").then(res=>res.json())

  return {
    props: {products}, // will be passed to the page component as props
  }
}